"I think a computer program is  a set of code that does  aspecefic thing"
"My favriote food is chicken  alfredo"
"you make alfredco by unthawing chicken"
"the second thing that you do is you season the noodles"
"the third thing that you do is season the noodles "
"the fourth thing that you do is you cook the noodles"
"the fith thing that you do is you season the chicken"
"the sixth  thing you do is make the chese sauce "
"the last and final step you do is put all the ingredients together"